spring:
  datasource:
    url: jdbc:mysql://5628e0ad1c559.sh.cdb.myqcloud.com:9993/chilopod?characterEncoding=utf8&useSSL=true
    username: cdb_outerroot
    password: shandelzare123
    driver-class-name: com.mysql.jdbc.Driver
  couchbase:
    bucket:
      name:
  jpa:
    hibernate:
      ddl-auto: update
slave:
  server:
    ip: 127.0.0.1:8002
  task:
    path: C:\project\stmt